

COUNTRIES = (("Andorra","Andorra"),
("United Arab Emirates","United Arab Emirates"),
("Afghanistan","Afghanistan"),
("Antigua and Barbuda","Antigua and Barbuda"),
("Anguilla","Anguilla"),
("Albania","Albania"),
("Armenia","Armenia"),
("Netherlands Antilles","Netherlands Antilles"),
("Angola","Angola"),
("Antarctica","Antarctica"),
("Argentina","Argentina"),
("American Samoa","American Samoa"),
("Austria","Austria"),
("Australia","Australia"),
("Aruba","Aruba"),
("Azerbaijan","Azerbaijan"),
("Bosnia and Herzegovina","Bosnia and Herzegovina"),
("Barbados","Barbados"),
("Bangladesh","Bangladesh"),
("Belgium","Belgium"),
("Burkina Faso","Burkina Faso"),
("Bulgaria","Bulgaria"),
("Bahrain","Bahrain"),
("Burundi","Burundi"),
("Benin","Benin"),
("Bermuda","Bermuda"),
("Brunei Darussalam","Brunei Darussalam"),
("Bolivia","Bolivia"),
("Brazil","Brazil"),
("Bahamas","Bahamas"),
("Bhutan","Bhutan"),
("Bouvet Island","Bouvet Island"),
("Botswana","Botswana"),
("Belarus","Belarus"),
("Belize","Belize"),
("Canada","Canada"),
("Cocos Keeling Islands","Cocos Keeling Islands"),
("Central African Republic","Central African Republic"),
("Congo","Congo"),
("Switzerland","Switzerland"),
("Cote D'Ivoire Ivory Coast","Cote D'Ivoire Ivory Coast"),
("Cook Islands","Cook Islands"),
("Chile","Chile"),
("Cameroon","Cameroon"),
("China","China"),
("Colombia","Colombia"),
("Costa Rica","Costa Rica"),
("Czechoslovakia former","Czechoslovakia former"),
("Cuba","Cuba"),
("Cape Verde","Cape Verde"),
("Christmas Island","Christmas Island"),
("Cyprus","Cyprus"),
("Czech Republic","Czech Republic"),
("Germany","Germany"),
("Djibouti","Djibouti"),
("Denmark","Denmark"),
("Dominica","Dominica"),
("Dominican Republic","Dominican Republic"),
("Algeria","Algeria"),
("Ecuador","Ecuador"),
("Estonia","Estonia"),
("Egypt","Egypt"),
("Western Sahara","Western Sahara"),
("Eritrea","Eritrea"),
("Spain","Spain"),
("Ethiopia","Ethiopia"),
("Finland","Finland"),
("Fiji","Fiji"),
("Micronesia","Micronesia"),
("Faroe Islands","Faroe Islands"),
("France","France"),
("France","France"),
("Gabon","Gabon"),
("Great Britain UK","Great Britain UK"),
("Grenada","Grenada"),
("Georgia","Georgia"),
("French Guiana","French Guiana"),
("Ghana","Ghana"),
("Gibraltar","Gibraltar"),
("Greenland","Greenland"),
("Gambia","Gambia"),
("Guinea","Guinea"),
("Guadeloupe","Guadeloupe"),
("Equatorial Guinea","Equatorial Guinea"),
("Greece","Greece"),
("Guatemala","Guatemala"),
("Guam","Guam"),
("Guinea-Bissau","Guinea-Bissau"),
("Guyana","Guyana"),
("Hong Kong","Hong Kong"),
("Heard and McDonald Islands","Heard and McDonald Islands"),
("Honduras","Honduras"),
("Croatia Hrvatska","Croatia Hrvatska"),
("Haiti","Haiti"),
("Hungary","Hungary"),
("Indonesia","Indonesia"),
("Ireland","Ireland"),
("Israel","Israel"),
("India","India"),
("British Indian Ocean Territory","British Indian Ocean Territory"),
("Iraq","Iraq"),
("Iran","Iran"),
("Iceland","Iceland"),
("Italy","Italy"),
("Jamaica","Jamaica"),
("Jordan","Jordan"),
("Japan","Japan"),
("Kenya","Kenya"),
("Kyrgyzstan","Kyrgyzstan"),
("Cambodia","Cambodia"),
("Kiribati","Kiribati"),
("Comoros","Comoros"),
("Saint Kitts and Nevis","Saint Kitts and Nevis"),
("Korea North","Korea North"),
("Korea South","Korea South"),
("Kuwait","Kuwait"),
("Cayman Islands","Cayman Islands"),
("Kazakhstan","Kazakhstan"),
("Laos","Laos"),
("Lebanon","Lebanon"),
("Saint Lucia","Saint Lucia"),
("Liechtenstein","Liechtenstein"),
("Sri Lanka","Sri Lanka"),
("Liberia","Liberia"),
("Lesotho","Lesotho"),
("Lithuania","Lithuania"),
("Luxembourg","Luxembourg"),
("Latvia","Latvia"),
("Libya","Libya"),
("Morocco","Morocco"),
("Monaco","Monaco"),
("Moldova","Moldova"),
("Madagascar","Madagascar"),
("Marshall Islands","Marshall Islands"),
("Macedonia","Macedonia"),
("Mali","Mali"),
("Myanmar","Myanmar"),
("Mongolia","Mongolia"),
("Macau","Macau"),
("Northern Mariana Islands","Northern Mariana Islands"),
("Martinique","Martinique"),
("Mauritania","Mauritania"),
("Montserrat","Montserrat"),
("Malta","Malta"),
("Mauritius","Mauritius"),
("Maldives","Maldives"),
("Malawi","Malawi"),
("Mexico","Mexico"),
("Malaysia","Malaysia"),
("Mozambique","Mozambique"),
("Namibia","Namibia"),
("New Caledonia","New Caledonia"),
("Niger","Niger"),
("Norfolk Island","Norfolk Island"),
("Nigeria","Nigeria"),
("Nicaragua","Nicaragua"),
("Netherlands","Netherlands"),
("Norway","Norway"),
("Nepal","Nepal"),
("Nauru","Nauru"),
("Neutral Zone","Neutral Zone"),
("Niue","Niue"),
("New Zealand Aotearoa","New Zealand Aotearoa"),
("Oman","Oman"),
("Panama","Panama"),
("Peru","Peru"),
("French Polynesia","French Polynesia"),
("Papua New Guinea","Papua New Guinea"),
("Philippines","Philippines"),
("Pakistan","Pakistan"),
("Poland","Poland"),
("St. Pierre and Miquelon","St. Pierre and Miquelon"),
("Pitcairn","Pitcairn"),
("Puerto Rico","Puerto Rico"),
("Portugal","Portugal"),
("Palau","Palau"),
("Paraguay","Paraguay"),
("Qatar","Qatar"),
("Reunion","Reunion"),
("Romania","Romania"),
("Russian Federation","Russian Federation"),
("Rwanda","Rwanda"),
("Saudi Arabia","Saudi Arabia"),
("Solomon Islands","Solomon Islands"),
("Seychelles","Seychelles"),
("Sudan","Sudan"),
("Sweden","Sweden"),
("Singapore","Singapore"),
("St. Helena","St. Helena"),
("Slovenia","Slovenia"),
("Svalbard and Jan Mayen Islands","Svalbard and Jan Mayen Islands"),
("Slovak Republic","Slovak Republic"),
("Sierra Leone","Sierra Leone"),
("San Marino","San Marino"),
("Senegal","Senegal"),
("Somalia","Somalia"),
("Suriname","Suriname"),
("Sao Tome and Principe","Sao Tome and Principe"),
("USSR former","USSR former"),
("El Salvador","El Salvador"),
("Syria","Syria"),
("Swaziland","Swaziland"),
("Turks and Caicos Islands","Turks and Caicos Islands"),
("Chad","Chad"),
("French Southern Territories","French Southern Territories"),
("Togo","Togo"),
("Thailand","Thailand"),
("Tajikistan","Tajikistan"),
("Tokelau","Tokelau"),
("Turkmenistan","Turkmenistan"),
("Tunisia","Tunisia"),
("Tonga","Tonga"),
("East Timor","East Timor"),
("Turkey","Turkey"),
("Trinidad and Tobago","Trinidad and Tobago"),
("Tuvalu","Tuvalu"),
("Taiwan","Taiwan"),
("Tanzania","Tanzania"),
("Ukraine","Ukraine"),
("Uganda","Uganda"),
("United Kingdom","United Kingdom"),
("US Minor Outlying Islands","US Minor Outlying Islands"),
("United States","United States"),
("Uruguay","Uruguay"),
("Uzbekistan","Uzbekistan"),
("Vatican City State Holy See","Vatican City State Holy See"),
("Venezuela","Venezuela"),
("Virgin Islands British","Virgin Islands British"),
("Virgin Islands U.S.","Virgin Islands U.S."),
("Viet Nam","Viet Nam"),
("Vanuatu","Vanuatu"),
("Wallis and Futuna Islands","Wallis and Futuna Islands"),
("Samoa","Samoa"),
("Yemen","Yemen"),
("Mayotte","Mayotte"),
("Yugoslavia","Yugoslavia"),
("South Africa","South Africa"),
("Zambia","Zambia"),
("Zaire","Zaire"),
("Zimbabwe","Zimbabwe"),
("Falkland Islands Malvinas","Falkland Islands Malvinas"),
("Saint Vincent and the Grenadines","Saint Vincent and the Grenadines"),
("S. Georgia and S. Sandwich Isls.","S. Georgia and S. Sandwich Isls."))